version: '2'
services:
  mongo:
    container_name: honeyDB
    image: mongo
  honeypress:
    container_name: honeypress
    build: ./honeypress/
    ports:
      - '80:80'
      - '8080'
    depends_on:
      - mongo
    links:
      - mongo
