version: '2'
services:
  mongo:
    container_name: honeyDB
    image: mongo
  honeypress:
    container_name: honeypress
    build: .
    ports:
      - '80:80'
    depends_on:
      - mongo
    links:
      - mongo
