version: '2'
services:
  mongo:
    container_name: honeyDB
    image: mongo
  honeypress:
    container_name: honeypress
    build: ./honeypress/
    ports:
      - '80:80'
    depends_on:
      - mongo
    links:
      - mongo
  dashboard:
    container_name: dashboard
    build: ./dashboard/
    ports:
      - '1337:1337'
    depends_on:
      - mongo
    links:
      - mongo
